
title: Rebecca Cottrell
tab_title: Rebecca Cottrell #This text shows up on the browser tab
email:
description:
url: "https://rcottrell.com" # the base hostname & protocol for your site


instagram_username: rapturebird




# Build settings
markdown: kramdown
plugins: 
- jekyll-seo-tag
